Сделал 7 заданий, застрял на 8-ом
korneevm/learn-homework-1 pull request #131
Opened 2023-02-18 01:56 UTC by Rukin17

2023-02-22 06:56 UTC, krepysh requested changes

2023-02-22 06:56 UTC, krepysh commented on 1_if1.py
> +def just_do_it(age):
Имя функции должно отражать что делает функция. Что-то вроде get_status_by_age было  бы лучше. Надо поменять.

2023-02-22 06:56 UTC, krepysh commented on 2_if2.py
> +    if type(text_1) == str and type(text_2) == str:
Лучше использовать isinstance вместо прямого сравнения типов.
isinstance делает более широкое сравнение.

2023-02-22 06:56 UTC, krepysh commented on 2_if2.py
> +        return ("0")
блок else можно убрать без потери смысла, просто return 0

2023-02-22 06:56 UTC, krepysh commented on 2_if2.py
> +            return ("1")
return не нужны скобки
Думаю, что тут не нужно было число в строку оборачивать - возвращай просто число.

2023-02-22 06:56 UTC, krepysh commented on 3_for.py
> +    s = 0
используй тут функцию summa

2023-02-22 06:56 UTC, krepysh commented on 4_while1.py
> +        if dialog == 'Хорошо':
совершенно не понятно, почему переменная должна называться dialog.
Попробуй придумать более понятное имя.

2023-02-22 06:56 UTC, krepysh commented on 8_ephem_bot.py
> +today = "2023/02/18"
datetime.today()

2023-02-22 06:56 UTC, krepysh commented on 8_ephem_bot.py
> +    if plan_name == "Mars":
попробуй тоже самое через словарь сделать:
```
planets = {"Mars": ephem.Mars}
planet = planets["Mars"]
planet(today)
```
В словаре можно хранить функции (без скобочек)

2023-02-26 21:49 UTC, Rukin17 commented
Осталось ephem исправить

2024-04-19 13:23 UTC, closed without merging